version: 2.1    
executors:
  golang-builder:
    docker: 
    - image: circleci/golang:1.12
jobs:
  build:
    executor: golang-builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Build and save Docker container
          command: make docker-save DOCKER_TAR_FILE=/tmp/workspace/docker-image.tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-image.tar
  release:
    executor: golang-builder
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker container
          command: make docker-load DOCKER_TAR_FILE=/tmp/workspace/docker-image.tar
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PWD"
      - run:
          name: Push Docker container
          command: make docker-push
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
