defaults: &defaults
  docker:
  - image: circleci/golang:1.12

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Build and save Docker container
          command: make docker-save DOCKER_TAR_FILE=docker-image.tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-image.tar
  release:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "23:30:b7:2a:e9:44:5f:d9:d0:fd:e9:ce:7b:1d:0a:96"
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker container
          command: make docker-load /tmp/workspace/docker-image.tar
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Push Docker container
          command: make docker-push
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
